version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dms-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - dms-network

  eureka-server:
    build:
      context: ./eureka-server
    container_name: dms-eureka
    ports:
      - "8761:8761"
    networks:
      - dms-network

  gateway:
    build:
      context: ./dms-gateway
    container_name: dms-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=veryLongAndSecureJwtSecretKeyForDmsApplication
    depends_on:
      - eureka-server
    networks:
      - dms-network

  auth-service:
    build:
      context: ./dms-auth-service
    container_name: dms-auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dms_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=veryLongAndSecureJwtSecretKeyForDmsApplication
    depends_on:
      - postgres
      - eureka-server
    networks:
      - dms-network

  user-service:
    build:
      context: ./dms-user-service
    container_name: dms-user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dms_user
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - postgres
      - eureka-server
    networks:
      - dms-network

  document-service:
    build:
      context: ./dms-document-service
    container_name: dms-document-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dms_document
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-dms-documents}
    depends_on:
      - postgres
      - eureka-server
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge

volumes:
  postgres-data:
