server:
  port: 8083

spring:
  application:
    name: dms-document-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dms_document
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucketName: ${S3_BUCKET_NAME:dms-documents}

management:
  endpoints:
    web:
      exposure:
        include: health,info
